### ISSUE TITLE
Zigbee2mqtt and mqttopenwb at the same time

### ISSUE THREAD

**Issue by Franko71** [a529987659852/openwbmqtt#12] opened 2021-11-13 13:31 UTC
Hi  I  had openwbmqtt running and working as sensors . Mqtt broker was the ip of the openwb. Now i installed the zigbee2mqtt and configured this. Thus it is not possible to configure mqtt a second time i dont know how to run openwbmqtt. I tried the mqtt  bridge  but am unsure what to consider in the config.

**Comment by slankes** [comment] 2021-12-20 13:41
Hello Franko71, 

what you are describing is not a bug/issue but a request for help. Github issues are not the best place for them.

I suggest to close this issue here and take the discussion to the openwb-forum.

You will either need to configure your local mqtt to add the openwb mqtt as "remote" or set-up the mqtt-bridge. Setting up the bridge is going to be the more complicated route as openwb requires a working tls certificate setup for your "other" broker.

**Closed** 2022-03-13 10:14 UTC
